# Generated by Django 5.2.13 on 2026-05-10 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oknardia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='sMetaDescription',
            field=models.CharField(blank=True, default='', help_text='SEO: описание для мета-тега (до 160 символов). Если пусто, будет использоваться текст тизера из контента.', max_length=160, verbose_name='Meta описание'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='sMetaKeywords',
            field=models.CharField(blank=True, default='', help_text='SEO: ключевые слова для мета-тега (до 256 символов). Если пусто, будет использоваться заголовок.', max_length=256, verbose_name='Meta ключевые слова'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='sSlug',
            field=models.SlugField(blank=True, help_text='SEO: URL-friendly версия заголовка (автоматически генерируется, если оставить пусто)', max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='dPostDataBegin',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 5, 10, 17, 39, 4, 114851), help_text='Если установить будущую дату, то в назначеное время пост появится автоматически.', verbose_name='Опубликован от'),
        ),
    ]
